spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/badminton
    username: badminton
    password: 8mondeo
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: tournament

  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  error:
    whitelabel:
      enabled: false   # Disable the default Whitelabel error page
    include-stacktrace: never # Do not include stack traces in the error response
    path: /error  # Map all errors to the /error path (handled by the CustomErrorController)